<?php

namespace Database\Seeders;

use Illuminate\Support\Str;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class PropertySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('properties')->insert([
            // Property 1
            [
                'user_id' => 1,
                'category_id' => 1,
                'location_id' => 4,
                'propertytype_id' => 1,
                'property_name' => 'Luxurious Downtown Penthouse',
                'property_slug' => Str::slug('Luxurious Downtown Penthouse'),
                'buy_rent_type' => 'buy',
                'price' => 750000.00,
                'discount_price' => 725000.00,
                'property_descriptions' => 'This stunning penthouse offers breathtaking panoramic city views. Located in the heart of the bustling downtown area, it features state-of-the-art appliances, an open-concept living space, and floor-to-ceiling windows. The master suite includes a private balcony and a spa-like ensuite bathroom. The building provides a host of amenities, including a rooftop pool, a fully equipped gym, and 24/7 concierge service. This is a rare opportunity to own a piece of urban luxury.
                The interior design is a blend of modern elegance and functional living. Every detail has been carefully considered to provide a comfortable and sophisticated lifestyle. The kitchen is a chef\'s dream with high-end stainless steel appliances and custom cabinetry. The spacious bedrooms are designed for relaxation, offering a tranquil retreat from city life. Experience the pinnacle of luxury living.',
                'property_id' => 'ZOP251C',
                'rooms' => 5,
                'garage_size' => '2 car',
                'bedroom' => 3,
                'year_build' => '01 April, 2019',
                'bath_rooms' => 4,
                'property_size' => '2500 sqft',
                'garaze_count' => 2,
                'amenities' => 'Pool, Gym, Balcony, Concierge',
                'address' => '123 Main Street',
                'country' => 'USA',
                'state_country' => 'New York',
                'neighborhood' => 'Midtown',
                'zip_postal_code' => '10001',
                'city' => 'New York City',
                'thumbnail' => 'upload/property/1.jpg',
                'longitude' => -73.9855,
                'latitude' => 40.7580,
                'page_statistics_image' => 'upload/property/static/1.jpg',
                'hot_property' => 1,
                'featured_property' => 1,
                'status' => 1,
                'created_at' => now(),
            ],
            // Property 2
            [
                'user_id' => 5,
                'category_id' => 2,
                'location_id' => 6,
                'propertytype_id' => 2,
                'property_name' => 'Cozy Suburban Family Home',
                'property_slug' => Str::slug('Cozy Suburban Family Home'),
                'buy_rent_type' => 'rent',
                'price' => 2500.00,
                'discount_price' => null,
                'property_descriptions' => 'Nestled in a quiet, family-friendly neighborhood, this charming home is perfect for a growing family. It features a spacious backyard, a large kitchen, and a cozy fireplace in the living room. The area is known for its excellent schools and parks, making it an ideal location for children. The property is conveniently located close to shopping centers and public transportation.
                The house offers a comfortable and welcoming atmosphere. The main floor has an open layout that connects the living, dining, and kitchen areas, perfect for entertaining. The bedrooms are located on the second floor, providing privacy and a quiet retreat. The backyard is fully fenced, offering a safe space for children and pets to play. This is a great opportunity to rent a beautiful home in a fantastic community.',
                'property_id' => 'ZOP252D',
                'rooms' => 4,
                'garage_size' => '1 car',
                'bedroom' => 4,
                'year_build' => '15 August, 2010',
                'bath_rooms' => 2,
                'property_size' => '1800 sqft',
                'garaze_count' => 1,
                'amenities' => 'Backyard, Fireplace, Pet-friendly',
                'address' => '456 Oak Street',
                'country' => 'USA',
                'state_country' => 'California',
                'neighborhood' => 'Greenwood',
                'zip_postal_code' => '90210',
                'city' => 'Beverly Hills',
                'thumbnail' => 'upload/property/2.jpg',
                'longitude' => -118.4068,
                'latitude' => 34.0736,
                'page_statistics_image' => 'upload/property/static/2.jpg',
                'hot_property' => 0,
                'featured_property' => 1,
                'status' => 1,
                'created_at' => now(),
            ],
            // Property 3
            [
                'user_id' => 8,
                'category_id' => 3,
                'location_id' => 1,
                'propertytype_id' => 3,
                'property_name' => 'Modern Lakeside Villa',
                'property_slug' => Str::slug('Modern Lakeside Villa'),
                'buy_rent_type' => 'buy',
                'price' => 1200000.00,
                'discount_price' => null,
                'property_descriptions' => 'Experience tranquility in this stunning lakeside villa. This property offers direct access to the lake, a private dock, and a beautiful infinity pool. The contemporary design features large windows that capture the serene water views from almost every room. The interior is spacious and filled with natural light, creating a peaceful and relaxing environment.
                This is the ultimate retreat for those seeking a luxurious and quiet lifestyle away from the city. The expansive outdoor area is perfect for hosting gatherings, with a large patio and a built-in BBQ. The master suite has a private balcony overlooking the lake, providing a perfect spot for morning coffee. The property also includes a separate guesthouse, ideal for visitors or as a home office.',
                'property_id' => 'ZOP253E',
                'rooms' => 6,
                'garage_size' => '3 car',
                'bedroom' => 5,
                'year_build' => '20 June, 2021',
                'bath_rooms' => 5,
                'property_size' => '4000 sqft',
                'garaze_count' => 3,
                'amenities' => 'Lake Access, Pool, Private Dock, Guesthouse',
                'address' => '789 Lake View Drive',
                'country' => 'Canada',
                'state_country' => 'Ontario',
                'neighborhood' => 'Lakefront Estates',
                'zip_postal_code' => 'L4G 1H8',
                'city' => 'Muskoka',
                'thumbnail' => 'upload/property/3.jpg',
                'longitude' => -79.4512,
                'latitude' => 45.0682,
                'page_statistics_image' => 'upload/property/static/3.jpg',
                'hot_property' => 1,
                'featured_property' => 0,
                'status' => 1,
                'created_at' => now(),
            ],
            // Property 4
            [
                'user_id' => 2,
                'category_id' => 4,
                'location_id' => 5,
                'propertytype_id' => 1,
                'property_name' => 'Chic Urban Studio Apartment',
                'property_slug' => Str::slug('Chic Urban Studio Apartment'),
                'buy_rent_type' => 'rent',
                'price' => 1800.00,
                'discount_price' => null,
                'property_descriptions' => 'This compact and stylish studio apartment is perfect for single professionals or students. It features a modern kitchenette, a cleverly designed sleeping area, and a clean, contemporary bathroom. Located in a lively neighborhood, it is within walking distance of cafes, restaurants, and public transport. The building offers a secure entrance and a communal laundry facility.
                The space is efficiently designed to maximize every square foot, providing a comfortable and functional living environment. The large windows let in plenty of natural light, making the apartment feel open and bright. The location is a major highlight, placing you right in the center of the city\'s vibrant cultural scene. It\'s an ideal home base for those who want to experience all that urban life has to offer.',
                'property_id' => 'ZOP254F',
                'rooms' => 1,
                'garage_size' => 'No garage',
                'bedroom' => 0,
                'year_build' => '10 December, 2015',
                'bath_rooms' => 1,
                'property_size' => '500 sqft',
                'garaze_count' => 0,
                'amenities' => 'Communal Laundry, Secure Access',
                'address' => '789 Urban Avenue',
                'country' => 'UK',
                'state_country' => 'London',
                'neighborhood' => 'Shoreditch',
                'zip_postal_code' => 'E1 6AN',
                'city' => 'London',
                'thumbnail' => 'upload/property/4.jpg',
                'longitude' => -0.0784,
                'latitude' => 51.5222,
                'page_statistics_image' => 'upload/property/static/4.jpg',
                'hot_property' => 0,
                'featured_property' => 0,
                'status' => 1,
                'created_at' => now(),
            ],
            // Property 5
            [
                'user_id' => 1,
                'category_id' => 5,
                'location_id' => 6,
                'propertytype_id' => 2,
                'property_name' => 'Spacious Family Villa',
                'property_slug' => Str::slug('Spacious Family Villa'),
                'buy_rent_type' => 'buy',
                'price' => 950000.00,
                'discount_price' => 920000.00,
                'property_descriptions' => 'This beautiful villa is a masterpiece of design and comfort, offering an unparalleled living experience. Located in a prime residential area, it boasts a large garden, a private swimming pool, and an outdoor BBQ area, perfect for entertaining guests. The villa features multiple living spaces, a state-of-the-art kitchen, and spacious bedrooms with walk-in closets.
                The property is designed with a focus on family living, providing ample space for everyone. The master bedroom has a private balcony with stunning views of the surrounding landscape. The garden is professionally landscaped, creating a serene and beautiful environment. With its high-end finishes and thoughtful layout, this villa offers a perfect blend of luxury and functionality. It’s a dream home for those seeking comfort and style.',
                'property_id' => 'ZOP255G',
                'rooms' => 7,
                'garage_size' => '3 car',
                'bedroom' => 6,
                'year_build' => '10 February, 2022',
                'bath_rooms' => 6,
                'property_size' => '5000 sqft',
                'garaze_count' => 3,
                'amenities' => 'Swimming Pool, Garden, BBQ Area, Balcony',
                'address' => '101 Rosewood Lane',
                'country' => 'USA',
                'state_country' => 'Florida',
                'neighborhood' => 'Palm Grove',
                'zip_postal_code' => '33101',
                'city' => 'Miami',
                'thumbnail' => 'upload/property/5.jpg',
                'longitude' => -80.1918,
                'latitude' => 25.7617,
                'page_statistics_image' => 'upload/property/static/5.jpg',
                'hot_property' => 1,
                'featured_property' => 1,
                'status' => 1,
                'created_at' => now(),
            ],
            // Property 6
            [
                'user_id' => 8,
                'category_id' => 6,
                'location_id' => 4,
                'propertytype_id' => 3,
                'property_name' => 'Mountain Retreat Log Cabin',
                'property_slug' => Str::slug('Mountain Retreat Log Cabin'),
                'buy_rent_type' => 'rent',
                'price' => 3000.00,
                'discount_price' => null,
                'property_descriptions' => 'Escape to nature in this rustic yet luxurious log cabin. Nestled in the mountains, this property offers ultimate privacy and breathtaking views. It features a large stone fireplace, a wrap-around deck, and a hot tub. The interior is designed with a cozy, cabin-like feel, and includes all modern amenities for a comfortable stay.
                The cabin is located near hiking trails and ski resorts, making it a perfect getaway for outdoor enthusiasts. The kitchen is fully equipped, and the living area is ideal for relaxing after a day of adventure. The bedrooms are spacious and comfortable, offering a peaceful night\'s sleep. This is an excellent opportunity to experience the serene beauty of the mountains without sacrificing comfort.',
                'property_id' => 'ZOP256H',
                'rooms' => 4,
                'garage_size' => '1 car',
                'bedroom' => 3,
                'year_build' => '05 September, 2018',
                'bath_rooms' => 3,
                'property_size' => '1500 sqft',
                'garaze_count' => 1,
                'amenities' => 'Fireplace, Hot Tub, Deck',
                'address' => '246 Forest Trail',
                'country' => 'USA',
                'state_country' => 'Colorado',
                'neighborhood' => 'Aspen Valley',
                'zip_postal_code' => '81611',
                'city' => 'Aspen',
                'thumbnail' => 'upload/property/6.jpg',
                'longitude' => -106.8236,
                'latitude' => 39.1911,
                'page_statistics_image' => 'upload/property/static/6.jpg',
                'hot_property' => 0,
                'featured_property' => 1,
                'status' => 1,
                'created_at' => now(),
            ],
            // Property 7
            [
                'user_id' => 4,
                'category_id' => 7,
                'location_id' => 1,
                'propertytype_id' => 1,
                'property_name' => 'Industrial Style Loft',
                'property_slug' => Str::slug('Industrial Style Loft'),
                'buy_rent_type' => 'buy',
                'price' => 550000.00,
                'discount_price' => 520000.00,
                'property_descriptions' => 'This unique loft apartment offers an open, industrial aesthetic with high ceilings and exposed brick. It is located in a trendy, converted warehouse building. The property features large windows, polished concrete floors, and a modern, minimalist kitchen. It\'s an excellent choice for artists, designers, or anyone who appreciates a raw, urban feel.
                The living space is incredibly versatile, with plenty of room to customize the layout. The building is situated in a vibrant arts district, with galleries, studios, and independent boutiques right on your doorstep. The rooftop terrace provides a great space to relax and enjoy city views. This is an opportunity to own a one-of-a-kind property in a sought-after urban location.',
                'property_id' => 'ZOP257I',
                'rooms' => 3,
                'garage_size' => 'No garage',
                'bedroom' => 1,
                'year_build' => '12 March, 2017',
                'bath_rooms' => 2,
                'property_size' => '1200 sqft',
                'garaze_count' => 0,
                'amenities' => 'Rooftop Terrace, Exposed Brick',
                'address' => '321 Warehouse Lane',
                'country' => 'Canada',
                'state_country' => 'British Columbia',
                'neighborhood' => 'Gastown',
                'zip_postal_code' => 'V6B 1P1',
                'city' => 'Vancouver',
                'thumbnail' => 'upload/property/7.jpg',
                'longitude' => -123.1077,
                'latitude' => 49.2827,
                'page_statistics_image' => 'upload/property/static/7.jpg',
                'hot_property' => 1,
                'featured_property' => 0,
                'status' => 1,
                'created_at' => now(),
            ],
            // Property 8
            [
                'user_id' => 3,
                'category_id' => 8,
                'location_id' => 5,
                'propertytype_id' => 2,
                'property_name' => 'Traditional Countryside Cottage',
                'property_slug' => Str::slug('Traditional Countryside Cottage'),
                'buy_rent_type' => 'rent',
                'price' => 1500.00,
                'discount_price' => null,
                'property_descriptions' => 'This charming countryside cottage is a peaceful escape from the hustle and bustle of city life. The property is surrounded by lush green fields and offers a tranquil environment. It features a cozy living room with a wood-burning stove, a quaint kitchen, and a lovely private garden with a patio.
                The cottage is full of character and original features, offering a unique and authentic living experience. It\'s an ideal home for those who enjoy gardening and a quiet, relaxed lifestyle. Despite its secluded location, it is only a short drive to the nearest village, which has a local shop and a pub. This is a perfect opportunity to rent a slice of classic countryside living.',
                'property_id' => 'ZOP258J',
                'rooms' => 3,
                'garage_size' => '1 car',
                'bedroom' => 2,
                'year_build' => '02 July, 1995',
                'bath_rooms' => 1,
                'property_size' => '1000 sqft',
                'garaze_count' => 1,
                'amenities' => 'Garden, Wood Stove, Patio',
                'address' => '987 Country Road',
                'country' => 'UK',
                'state_country' => 'Cotswolds',
                'neighborhood' => 'Little Compton',
                'zip_postal_code' => 'GL56 0QZ',
                'city' => 'Gloucestershire',
                'thumbnail' => 'upload/property/8.jpg',
                'longitude' => -1.6917,
                'latitude' => 51.9806,
                'page_statistics_image' => 'upload/property/static/8.jpg',
                'hot_property' => 0,
                'featured_property' => 0,
                'status' => 1,
                'created_at' => now(),
            ],
            // Property 9
            [
                'user_id' => 6,
                'category_id' => 9,
                'location_id' => 4,
                'propertytype_id' => 3,
                'property_name' => 'Spacious Multi-Family Duplex',
                'property_slug' => Str::slug('Spacious Multi-Family Duplex'),
                'buy_rent_type' => 'buy',
                'price' => 850000.00,
                'discount_price' => 830000.00,
                'property_descriptions' => 'This well-maintained duplex is an excellent investment opportunity or an ideal home for an extended family. Each unit has its own private entrance, a full kitchen, and separate living spaces. The property is located in a desirable neighborhood with easy access to public transport, schools, and parks.
                Both units are currently rented, providing an immediate source of rental income. The property also has a shared backyard and a two-car garage. It is an ideal property for investors looking for a reliable source of passive income. The location is highly sought after, ensuring a high occupancy rate. This is a great chance to own a versatile property with a lot of potential.',
                'property_id' => 'ZOP259K',
                'rooms' => 8,
                'garage_size' => '2 car',
                'bedroom' => 4,
                'year_build' => '25 May, 2012',
                'bath_rooms' => 4,
                'property_size' => '3000 sqft',
                'garaze_count' => 2,
                'amenities' => 'Separate Entrances, Backyard, Duplex',
                'address' => '450 Investment Ave',
                'country' => 'USA',
                'state_country' => 'Texas',
                'neighborhood' => 'Oakwood',
                'zip_postal_code' => '73301',
                'city' => 'Austin',
                'thumbnail' => 'upload/property/9.jpg',
                'longitude' => -97.7431,
                'latitude' => 30.2672,
                'page_statistics_image' => 'upload/property/static/9.jpg',
                'hot_property' => 1,
                'featured_property' => 1,
                'status' => 1,
                'created_at' => now(),
            ],
            // Property 10
            [
                'user_id' => 7,
                'category_id' => 10,
                'location_id' => 6,
                'propertytype_id' => 1,
                'property_name' => 'High-End Oceanfront Condo',
                'property_slug' => Str::slug('High-End Oceanfront Condo'),
                'buy_rent_type' => 'rent',
                'price' => 6000.00,
                'discount_price' => null,
                'property_descriptions' => 'Wake up to the sound of the ocean in this stunning high-end condo. It features a private balcony with direct ocean views, a modern kitchen with granite countertops, and a spacious master bedroom. The building offers luxury amenities, including a private beach, a large pool, a fitness center, and 24/7 security.
                This is the perfect rental for those who desire a luxurious, resort-like lifestyle. The open-concept living area is perfect for enjoying the breathtaking sunset views. The condo is located in a prestigious area, close to high-end restaurants and boutiques. The property is meticulously maintained and offers a sense of privacy and tranquility. Experience the best of coastal living in this exceptional condo.',
                'property_id' => 'ZOP260L',
                'rooms' => 4,
                'garage_size' => '1 car',
                'bedroom' => 2,
                'year_build' => '18 January, 2020',
                'bath_rooms' => 3,
                'property_size' => '1600 sqft',
                'garaze_count' => 1,
                'amenities' => 'Ocean View, Pool, Gym, Private Beach',
                'address' => '55 Ocean Boulevard',
                'country' => 'USA',
                'state_country' => 'California',
                'neighborhood' => 'Malibu',
                'zip_postal_code' => '90265',
                'city' => 'Malibu',
                'thumbnail' => 'upload/property/10.jpg',
                'longitude' => -118.6892,
                'latitude' => 34.0386,
                'page_statistics_image' => 'upload/property/static/10.jpg',
                'hot_property' => 1,
                'featured_property' => 1,
                'status' => 1,
                'created_at' => now(),
            ],
        ]);
    }
}
