<?php

namespace Database\Seeders;

use Illuminate\Support\Str;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = [
            [
                'name' => 'Mehedi Hassan Jibon',
                'email' => 'mjjibon114@gmail.com',
                'username' => 'jibonbd360',
                'phone' => '01873593399',
                'photo' => null,
                'address' => 'Rangpur, Bangladesh',
                'email_verified_at' => '2025-08-15 10:00:00',
                'password' => Hash::make('111'),
                'credit' => 1500.5,
                'profession' => 'Software Engineer',
                'facebook' => 'https://facebook.com/rahim.ahmed',
                'twitter' => 'https://twitter.com/rahim.ahmed',
                'google' => 'https://google.com/rahim.ahmed',
                'role' => 'admin',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 10:00:00',
                'updated_at' => '2025-08-15 10:00:00',
            ],
            [
                'name' => 'Rahim Ahmed',
                'email' => 'rahim.ahmed@example.com',
                'username' => 'rahim.ahmed',
                'phone' => '01712345678',
                'photo' => null,
                'address' => 'Dhaka, Bangladesh',
                'email_verified_at' => '2025-08-15 10:00:00',
                'password' => Hash::make('111'),
                'credit' => 1500.5,
                'profession' => 'Software Engineer',
                'facebook' => 'https://facebook.com/rahim.ahmed',
                'twitter' => 'https://twitter.com/rahim.ahmed',
                'google' => 'https://google.com/rahim.ahmed',
                'role' => 'user',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 10:00:00',
                'updated_at' => '2025-08-15 10:00:00',
            ],
            [
                'name' => 'Karim Hossain',
                'email' => 'karim.hossain@example.com',
                'username' => 'karim.hossain',
                'phone' => '01812345678',
                'photo' => null,
                'address' => 'Chittagong, Bangladesh',
                'email_verified_at' => '2025-08-15 10:05:00',
                'password' => Hash::make('111'),
                'credit' => 2500.75,
                'profession' => 'Web Developer',
                'facebook' => 'https://facebook.com/karim.hossain',
                'twitter' => 'https://twitter.com/karim.hossain',
                'google' => 'https://google.com/karim.hossain',
                'role' => 'agent',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 10:05:00',
                'updated_at' => '2025-08-15 10:05:00',
            ],
            [
                'name' => 'Fahim Shahriar',
                'email' => 'fahim.shahriar@example.com',
                'username' => 'fahim.shahriar',
                'phone' => '01912345678',
                'photo' => null,
                'address' => 'Rajshahi, Bangladesh',
                'email_verified_at' => '2025-08-15 10:10:00',
                'password' => Hash::make('111'),
                'credit' => 5000.00,
                'profession' => 'Project Manager',
                'facebook' => 'https://facebook.com/fahim.shahriar',
                'twitter' => 'https://twitter.com/fahim.shahriar',
                'google' => 'https://google.com/fahim.shahriar',
                'role' => 'admin',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 10:10:00',
                'updated_at' => '2025-08-15 10:10:00',
            ],
            [
                'name' => 'Naimur Rahman',
                'email' => 'naimur.rahman@example.com',
                'username' => 'naimur.rahman',
                'phone' => '01512345678',
                'photo' => null,
                'address' => 'Khulna, Bangladesh',
                'email_verified_at' => '2025-08-15 10:15:00',
                'password' => Hash::make('111'),
                'credit' => 1200.00,
                'profession' => 'UI/UX Designer',
                'facebook' => 'https://facebook.com/naimur.rahman',
                'twitter' => 'https://twitter.com/naimur.rahman',
                'google' => 'https://google.com/naimur.rahman',
                'role' => 'user',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 10:15:00',
                'updated_at' => '2025-08-15 10:15:00',
            ],
            [
                'name' => 'Zahidul Islam',
                'email' => 'zahidul.islam@example.com',
                'username' => 'zahidul.islam',
                'phone' => '01612345678',
                'photo' => null,
                'address' => 'Sylhet, Bangladesh',
                'email_verified_at' => '2025-08-15 10:20:00',
                'password' => Hash::make('111'),
                'credit' => 800.25,
                'profession' => 'Data Scientist',
                'facebook' => 'https://facebook.com/zahidul.islam',
                'twitter' => 'https://twitter.com/zahidul.islam',
                'google' => 'https://google.com/zahidul.islam',
                'role' => 'agent',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 10:20:00',
                'updated_at' => '2025-08-15 10:20:00',
            ],
            [
                'name' => 'Sumon Ahmed',
                'email' => 'sumon.ahmed@example.com',
                'username' => 'sumon.ahmed',
                'phone' => '01723456789',
                'photo' => null,
                'address' => 'Barisal, Bangladesh',
                'email_verified_at' => '2025-08-15 10:25:00',
                'password' => Hash::make('111'),
                'credit' => 3500.00,
                'profession' => 'Network Engineer',
                'facebook' => 'https://facebook.com/sumon.ahmed',
                'twitter' => 'https://twitter.com/sumon.ahmed',
                'google' => 'https://google.com/sumon.ahmed',
                'role' => 'user',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 10:25:00',
                'updated_at' => '2025-08-15 10:25:00',
            ],
            [
                'name' => 'Nusrat Jahan',
                'email' => 'nusrat.jahan@example.com',
                'username' => 'nusrat.jahan',
                'phone' => '01823456789',
                'photo' => null,
                'address' => 'Rangpur, Bangladesh',
                'email_verified_at' => '2025-08-15 10:30:00',
                'password' => Hash::make('111'),
                'credit' => 950.50,
                'profession' => 'Graphic Designer',
                'facebook' => 'https://facebook.com/nusrat.jahan',
                'twitter' => 'https://twitter.com/nusrat.jahan',
                'google' => 'https://google.com/nusrat.jahan',
                'role' => 'agent',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 10:30:00',
                'updated_at' => '2025-08-15 10:30:00',
            ],
            [
                'name' => 'Tariqul Islam',
                'email' => 'tariqul.islam@example.com',
                'username' => 'tariqul.islam',
                'phone' => '01923456789',
                'photo' => null,
                'address' => 'Mymensingh, Bangladesh',
                'email_verified_at' => '2025-08-15 10:35:00',
                'password' => Hash::make('111'),
                'credit' => 4000.00,
                'profession' => 'DevOps Engineer',
                'facebook' => 'https://facebook.com/tariqul.islam',
                'twitter' => 'https://twitter.com/tariqul.islam',
                'google' => 'https://google.com/tariqul.islam',
                'role' => 'admin',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 10:35:00',
                'updated_at' => '2025-08-15 10:35:00',
            ],
            [
                'name' => 'Sadia Akhter',
                'email' => 'sadia.akhter@example.com',
                'username' => 'sadia.akhter',
                'phone' => '01523456789',
                'photo' => null,
                'address' => 'Gazipur, Bangladesh',
                'email_verified_at' => '2025-08-15 10:40:00',
                'password' => Hash::make('111'),
                'credit' => 600.00,
                'profession' => 'Content Writer',
                'facebook' => 'https://facebook.com/sadia.akhter',
                'twitter' => 'https://twitter.com/sadia.akhter',
                'google' => 'https://google.com/sadia.akhter',
                'role' => 'user',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 10:40:00',
                'updated_at' => '2025-08-15 10:40:00',
            ],
            [
                'name' => 'Kamrul Hasan',
                'email' => 'kamrul.hasan@example.com',
                'username' => 'kamrul.hasan',
                'phone' => '01623456789',
                'photo' => null,
                'address' => 'Narayanganj, Bangladesh',
                'email_verified_at' => '2025-08-15 10:45:00',
                'password' => Hash::make('111'),
                'credit' => 1800.50,
                'profession' => 'Mobile App Developer',
                'facebook' => 'https://facebook.com/kamrul.hasan',
                'twitter' => 'https://twitter.com/kamrul.hasan',
                'google' => 'https://google.com/kamrul.hasan',
                'role' => 'agent',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 10:45:00',
                'updated_at' => '2025-08-15 10:45:00',
            ],
            [
                'name' => 'Sajidul Karim',
                'email' => 'sajidul.karim@example.com',
                'username' => 'sajidul.karim',
                'phone' => '01734567890',
                'photo' => null,
                'address' => 'Cox\'s Bazar, Bangladesh',
                'email_verified_at' => '2025-08-15 10:50:00',
                'password' => Hash::make('111'),
                'credit' => 750.25,
                'profession' => 'Cyber Security Analyst',
                'facebook' => 'https://facebook.com/sajidul.karim',
                'twitter' => 'https://twitter.com/sajidul.karim',
                'google' => 'https://google.com/sajidul.karim',
                'role' => 'user',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 10:50:00',
                'updated_at' => '2025-08-15 10:50:00',
            ],
            [
                'name' => 'Mehedi Hasan',
                'email' => 'mehedi.hasan@example.com',
                'username' => 'mehedi.hasan',
                'phone' => '01834567890',
                'photo' => null,
                'address' => 'Dinajpur, Bangladesh',
                'email_verified_at' => '2025-08-15 10:55:00',
                'password' => Hash::make('111'),
                'credit' => 2000.00,
                'profession' => 'Machine Learning Engineer',
                'facebook' => 'https://facebook.com/mehedi.hasan',
                'twitter' => 'https://twitter.com/mehedi.hasan',
                'google' => 'https://google.com/mehedi.hasan',
                'role' => 'agent',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 10:55:00',
                'updated_at' => '2025-08-15 10:55:00',
            ],
            [
                'name' => 'Sharmin Sultana',
                'email' => 'sharmin.sultana@example.com',
                'username' => 'sharmin.sultana',
                'phone' => '01934567890',
                'photo' => null,
                'address' => 'Bogra, Bangladesh',
                'email_verified_at' => '2025-08-15 11:00:00',
                'password' => Hash::make('111'),
                'credit' => 300.00,
                'profession' => 'Social Media Manager',
                'facebook' => 'https://facebook.com/sharmin.sultana',
                'twitter' => 'https://twitter.com/sharmin.sultana',
                'google' => 'https://google.com/sharmin.sultana',
                'role' => 'user',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 11:00:00',
                'updated_at' => '2025-08-15 11:00:00',
            ],
            [
                'name' => 'Imran Khan',
                'email' => 'imran.khan@example.com',
                'username' => 'imran.khan',
                'phone' => '01534567890',
                'photo' => null,
                'address' => 'Jessore, Bangladesh',
                'email_verified_at' => '2025-08-15 11:05:00',
                'password' => Hash::make('111'),
                'credit' => 4500.50,
                'profession' => 'Database Administrator',
                'facebook' => 'https://facebook.com/imran.khan',
                'twitter' => 'https://twitter.com/imran.khan',
                'google' => 'https://google.com/imran.khan',
                'role' => 'admin',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 11:05:00',
                'updated_at' => '2025-08-15 11:05:00',
            ],
            [
                'name' => 'Rafiqul Islam',
                'email' => 'rafiqul.islam@example.com',
                'username' => 'rafiqul.islam',
                'phone' => '01634567890',
                'photo' => null,
                'address' => 'Pabna, Bangladesh',
                'email_verified_at' => '2025-08-15 11:10:00',
                'password' => Hash::make('111'),
                'credit' => 1000.00,
                'profession' => 'System Administrator',
                'facebook' => 'https://facebook.com/rafiqul.islam',
                'twitter' => 'https://twitter.com/rafiqul.islam',
                'google' => 'https://google.com/rafiqul.islam',
                'role' => 'user',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 11:10:00',
                'updated_at' => '2025-08-15 11:10:00',
            ],
            [
                'name' => 'Sonia Akter',
                'email' => 'sonia.akter@example.com',
                'username' => 'sonia.akter',
                'phone' => '01745678901',
                'photo' => null,
                'address' => 'Tangail, Bangladesh',
                'email_verified_at' => '2025-08-15 11:15:00',
                'password' => Hash::make('111'),
                'credit' => 2500.00,
                'profession' => 'Marketing Manager',
                'facebook' => 'https://facebook.com/sonia.akter',
                'twitter' => 'https://twitter.com/sonia.akter',
                'google' => 'https://google.com/sonia.akter',
                'role' => 'agent',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 11:15:00',
                'updated_at' => '2025-08-15 11:15:00',
            ],
            [
                'name' => 'Arif Islam',
                'email' => 'arif.islam@example.com',
                'username' => 'arif.islam',
                'phone' => '01845678901',
                'photo' => null,
                'address' => 'Brahmanbaria, Bangladesh',
                'email_verified_at' => '2025-08-15 11:20:00',
                'password' => Hash::make('111'),
                'credit' => 800.00,
                'profession' => 'Cloud Engineer',
                'facebook' => 'https://facebook.com/arif.islam',
                'twitter' => 'https://twitter.com/arif.islam',
                'google' => 'https://google.com/arif.islam',
                'role' => 'user',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 11:20:00',
                'updated_at' => '2025-08-15 11:20:00',
            ],
            [
                'name' => 'Rina Akter',
                'email' => 'rina.akter@example.com',
                'username' => 'rina.akter',
                'phone' => '01945678901',
                'photo' => null,
                'address' => 'Comilla, Bangladesh',
                'email_verified_at' => '2025-08-15 11:25:00',
                'password' => Hash::make('111'),
                'credit' => 3500.50,
                'profession' => 'UX Researcher',
                'facebook' => 'https://facebook.com/rina.akter',
                'twitter' => 'https://twitter.com/rina.akter',
                'google' => 'https://google.com/rina.akter',
                'role' => 'agent',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 11:25:00',
                'updated_at' => '2025-08-15 11:25:00',
            ],
            [
                'name' => 'Sakib Al Hasan',
                'email' => 'sakib.alhasan@example.com',
                'username' => 'sakib.alhasan',
                'phone' => '01545678901',
                'photo' => null,
                'address' => 'Dhaka, Bangladesh',
                'email_verified_at' => '2025-08-15 11:30:00',
                'password' => Hash::make('111'),
                'credit' => 500.00,
                'profession' => 'Digital Marketer',
                'facebook' => 'https://facebook.com/sakib.alhasan',
                'twitter' => 'https://twitter.com/sakib.alhasan',
                'google' => 'https://google.com/sakib.alhasan',
                'role' => 'admin',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 11:30:00',
                'updated_at' => '2025-08-15 11:30:00',
            ],
            [
                'name' => 'Tamim Iqbal',
                'email' => 'tamim.iqbal@example.com',
                'username' => 'tamim.iqbal',
                'phone' => '01645678901',
                'photo' => null,
                'address' => 'Chittagong, Bangladesh',
                'email_verified_at' => '2025-08-15 11:35:00',
                'password' => Hash::make('111'),
                'credit' => 1500.00,
                'profession' => 'SEO Specialist',
                'facebook' => 'https://facebook.com/tamim.iqbal',
                'twitter' => 'https://twitter.com/tamim.iqbal',
                'google' => 'https://google.com/tamim.iqbal',
                'role' => 'user',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 11:35:00',
                'updated_at' => '2025-08-15 11:35:00',
            ],
            [
                'name' => 'Mushfiqur Rahim',
                'email' => 'mushfiqur.rahim@example.com',
                'username' => 'mushfiqur.rahim',
                'phone' => '01756789012',
                'photo' => null,
                'address' => 'Rajshahi, Bangladesh',
                'email_verified_at' => '2025-08-15 11:40:00',
                'password' => Hash::make('111'),
                'credit' => 2500.50,
                'profession' => 'Full-Stack Developer',
                'facebook' => 'https://facebook.com/mushfiqur.rahim',
                'twitter' => 'https://twitter.com/mushfiqur.rahim',
                'google' => 'https://google.com/mushfiqur.rahim',
                'role' => 'agent',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 11:40:00',
                'updated_at' => '2025-08-15 11:40:00',
            ],
            [
                'name' => 'Mahmudullah Riyad',
                'email' => 'mahmudullah.riyad@example.com',
                'username' => 'mahmudullah.riyad',
                'phone' => '01856789012',
                'photo' => null,
                'address' => 'Khulna, Bangladesh',
                'email_verified_at' => '2025-08-15 11:45:00',
                'password' => Hash::make('111'),
                'credit' => 1800.00,
                'profession' => 'Backend Developer',
                'facebook' => 'https://facebook.com/mahmudullah.riyad',
                'twitter' => 'https://twitter.com/mahmudullah.riyad',
                'google' => 'https://google.com/mahmudullah.riyad',
                'role' => 'user',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 11:45:00',
                'updated_at' => '2025-08-15 11:45:00',
            ],
            [
                'name' => 'Mashrafe Mortaza',
                'email' => 'mashrafe.mortaza@example.com',
                'username' => 'mashrafe.mortaza',
                'phone' => '01956789012',
                'photo' => null,
                'address' => 'Sylhet, Bangladesh',
                'email_verified_at' => '2025-08-15 11:50:00',
                'password' => Hash::make('111'),
                'credit' => 5000.50,
                'profession' => 'Frontend Developer',
                'facebook' => 'https://facebook.com/mashrafe.mortaza',
                'twitter' => 'https://twitter.com/mashrafe.mortaza',
                'google' => 'https://google.com/mashrafe.mortaza',
                'role' => 'admin',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 11:50:00',
                'updated_at' => '2025-08-15 11:50:00',
            ],
            [
                'name' => 'Mustafizur Rahman',
                'email' => 'mustafizur.rahman@example.com',
                'username' => 'mustafizur.rahman',
                'phone' => '01556789012',
                'photo' => null,
                'address' => 'Barisal, Bangladesh',
                'email_verified_at' => '2025-08-15 11:55:00',
                'password' => Hash::make('111'),
                'credit' => 900.00,
                'profession' => 'Game Developer',
                'facebook' => 'https://facebook.com/mustafizur.rahman',
                'twitter' => 'https://twitter.com/mustafizur.rahman',
                'google' => 'https://google.com/mustafizur.rahman',
                'role' => 'user',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 11:55:00',
                'updated_at' => '2025-08-15 11:55:00',
            ],
            [
                'name' => 'Liton Das',
                'email' => 'liton.das@example.com',
                'username' => 'liton.das',
                'phone' => '01656789012',
                'photo' => null,
                'address' => 'Rangpur, Bangladesh',
                'email_verified_at' => '2025-08-15 12:00:00',
                'password' => Hash::make('111'),
                'credit' => 1200.50,
                'profession' => 'Mobile QA Engineer',
                'facebook' => 'https://facebook.com/liton.das',
                'twitter' => 'https://twitter.com/liton.das',
                'google' => 'https://google.com/liton.das',
                'role' => 'agent',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 12:00:00',
                'updated_at' => '2025-08-15 12:00:00',
            ],
            [
                'name' => 'Soumya Sarkar',
                'email' => 'soumya.sarkar@example.com',
                'username' => 'soumya.sarkar',
                'phone' => '01767890123',
                'photo' => null,
                'address' => 'Mymensingh, Bangladesh',
                'email_verified_at' => '2025-08-15 12:05:00',
                'password' => Hash::make('111'),
                'credit' => 3000.00,
                'profession' => 'Software Tester',
                'facebook' => 'https://facebook.com/soumya.sarkar',
                'twitter' => 'https://twitter.com/soumya.sarkar',
                'google' => 'https://google.com/soumya.sarkar',
                'role' => 'user',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 12:05:00',
                'updated_at' => '2025-08-15 12:05:00',
            ],
            [
                'name' => 'Taskin Ahmed',
                'email' => 'taskin.ahmed@example.com',
                'username' => 'taskin.ahmed',
                'phone' => '01867890123',
                'photo' => null,
                'address' => 'Gazipur, Bangladesh',
                'email_verified_at' => '2025-08-15 12:10:00',
                'password' => Hash::make('111'),
                'credit' => 1000.00,
                'profession' => 'UI Designer',
                'facebook' => 'https://facebook.com/taskin.ahmed',
                'twitter' => 'https://twitter.com/taskin.ahmed',
                'google' => 'https://google.com/taskin.ahmed',
                'role' => 'agent',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 12:10:00',
                'updated_at' => '2025-08-15 12:10:00',
            ],
            [
                'name' => 'Rubel Hossain',
                'email' => 'rubel.hossain@example.com',
                'username' => 'rubel.hossain',
                'phone' => '01967890123',
                'photo' => null,
                'address' => 'Narayanganj, Bangladesh',
                'email_verified_at' => '2025-08-15 12:15:00',
                'password' => Hash::make('111'),
                'credit' => 400.00,
                'profession' => 'IT Support Specialist',
                'facebook' => 'https://facebook.com/rubel.hossain',
                'twitter' => 'https://twitter.com/rubel.hossain',
                'google' => 'https://google.com/rubel.hossain',
                'role' => 'user',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 12:15:00',
                'updated_at' => '2025-08-15 12:15:00',
            ],
            [
                'name' => 'Shuvagata Hom',
                'email' => 'shuvagata.hom@example.com',
                'username' => 'shuvagata.hom',
                'phone' => '01567890123',
                'photo' => null,
                'address' => 'Cox\'s Bazar, Bangladesh',
                'email_verified_at' => '2025-08-15 12:20:00',
                'password' => Hash::make('111'),
                'credit' => 2000.00,
                'profession' => 'Frontend Engineer',
                'facebook' => 'https://facebook.com/shuvagata.hom',
                'twitter' => 'https://twitter.com/shuvagata.hom',
                'google' => 'https://google.com/shuvagata.hom',
                'role' => 'agent',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 12:20:00',
                'updated_at' => '2025-08-15 12:20:00',
            ],
            [
                'name' => 'Al-Amin Hossain',
                'email' => 'al.amin@example.com',
                'username' => 'al.amin',
                'phone' => '01667890123',
                'photo' => null,
                'address' => 'Dinajpur, Bangladesh',
                'email_verified_at' => '2025-08-15 12:25:00',
                'password' => Hash::make('111'),
                'credit' => 6000.00,
                'profession' => 'Software Architect',
                'facebook' => 'https://facebook.com/al.amin',
                'twitter' => 'https://twitter.com/al.amin',
                'google' => 'https://google.com/al.amin',
                'role' => 'admin',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 12:25:00',
                'updated_at' => '2025-08-15 12:25:00',
            ],
            [
                'name' => 'Mominul Haque',
                'email' => 'mominul.haque@example.com',
                'username' => 'mominul.haque',
                'phone' => '01778901234',
                'photo' => null,
                'address' => 'Khulna, Bangladesh',
                'email_verified_at' => '2025-08-15 12:30:00',
                'password' => Hash::make('111'),
                'credit' => 1500.00,
                'profession' => 'IT Consultant',
                'facebook' => 'https://facebook.com/mominul.haque',
                'twitter' => 'https://twitter.com/mominul.haque',
                'google' => 'https://google.com/mominul.haque',
                'role' => 'user',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 12:30:00',
                'updated_at' => '2025-08-15 12:30:00',
            ],
            [
                'name' => 'Md. Ashraful',
                'email' => 'md.ashraful@example.com',
                'username' => 'md.ashraful',
                'phone' => '01878901234',
                'photo' => null,
                'address' => 'Dhaka, Bangladesh',
                'email_verified_at' => '2025-08-15 12:35:00',
                'password' => Hash::make('111'),
                'credit' => 2500.00,
                'profession' => 'Business Analyst',
                'facebook' => 'https://facebook.com/md.ashraful',
                'twitter' => 'https://twitter.com/md.ashraful',
                'google' => 'https://google.com/md.ashraful',
                'role' => 'agent',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 12:35:00',
                'updated_at' => '2025-08-15 12:35:00',
            ],
            [
                'name' => 'Nasir Hossain',
                'email' => 'nasir.hossain@example.com',
                'username' => 'nasir.hossain',
                'phone' => '01978901234',
                'photo' => null,
                'address' => 'Rangpur, Bangladesh',
                'email_verified_at' => '2025-08-15 12:40:00',
                'password' => Hash::make('111'),
                'credit' => 800.00,
                'profession' => 'Database Developer',
                'facebook' => 'https://facebook.com/nasir.hossain',
                'twitter' => 'https://twitter.com/nasir.hossain',
                'google' => 'https://google.com/nasir.hossain',
                'role' => 'user',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 12:40:00',
                'updated_at' => '2025-08-15 12:40:00',
            ],
            [
                'name' => 'Abdur Razzak',
                'email' => 'abdur.razzak@example.com',
                'username' => 'abdur.razzak',
                'phone' => '01578901234',
                'photo' => null,
                'address' => 'Chittagong, Bangladesh',
                'email_verified_at' => '2025-08-15 12:45:00',
                'password' => Hash::make('111'),
                'credit' => 3500.00,
                'profession' => 'System Analyst',
                'facebook' => 'https://facebook.com/abdur.razzak',
                'twitter' => 'https://twitter.com/abdur.razzak',
                'google' => 'https://google.com/abdur.razzak',
                'role' => 'admin',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 12:45:00',
                'updated_at' => '2025-08-15 12:45:00',
            ],
            [
                'name' => 'Arafat Sunny',
                'email' => 'arafat.sunny@example.com',
                'username' => 'arafat.sunny',
                'phone' => '01678901234',
                'photo' => null,
                'address' => 'Rajshahi, Bangladesh',
                'email_verified_at' => '2025-08-15 12:50:00',
                'password' => Hash::make('111'),
                'credit' => 1200.00,
                'profession' => 'Mobile Engineer',
                'facebook' => 'https://facebook.com/arafat.sunny',
                'twitter' => 'https://twitter.com/arafat.sunny',
                'google' => 'https://google.com/arafat.sunny',
                'role' => 'user',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 12:50:00',
                'updated_at' => '2025-08-15 12:50:00',
            ],
            [
                'name' => 'Junaid Siddique',
                'email' => 'junaid.siddique@example.com',
                'username' => 'junaid.siddique',
                'phone' => '01789012345',
                'photo' => null,
                'address' => 'Sylhet, Bangladesh',
                'email_verified_at' => '2025-08-15 12:55:00',
                'password' => Hash::make('111'),
                'credit' => 950.25,
                'profession' => 'Frontend Architect',
                'facebook' => 'https://facebook.com/junaid.siddique',
                'twitter' => 'https://twitter.com/junaid.siddique',
                'google' => 'https://google.com/junaid.siddique',
                'role' => 'agent',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 12:55:00',
                'updated_at' => '2025-08-15 12:55:00',
            ],
            [
                'name' => 'Anamul Haque',
                'email' => 'anamul.haque@example.com',
                'username' => 'anamul.haque',
                'phone' => '01889012345',
                'photo' => null,
                'address' => 'Barisal, Bangladesh',
                'email_verified_at' => '2025-08-15 13:00:00',
                'password' => Hash::make('111'),
                'credit' => 2000.00,
                'profession' => 'Product Manager',
                'facebook' => 'https://facebook.com/anamul.haque',
                'twitter' => 'https://twitter.com/anamul.haque',
                'google' => 'https://google.com/anamul.haque',
                'role' => 'user',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 13:00:00',
                'updated_at' => '2025-08-15 13:00:00',
            ],
            [
                'name' => 'Mohammad Mithun',
                'email' => 'mohammad.mithun@example.com',
                'username' => 'mohammad.mithun',
                'phone' => '01989012345',
                'photo' => null,
                'address' => 'Mymensingh, Bangladesh',
                'email_verified_at' => '2025-08-15 13:05:00',
                'password' => Hash::make('111'),
                'credit' => 3000.00,
                'profession' => 'Project Coordinator',
                'facebook' => 'https://facebook.com/mohammad.mithun',
                'twitter' => 'https://twitter.com/mohammad.mithun',
                'google' => 'https://google.com/mohammad.mithun',
                'role' => 'agent',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 13:05:00',
                'updated_at' => '2025-08-15 13:05:00',
            ],
            [
                'name' => 'Shamsur Rahman',
                'email' => 'shamsur.rahman@example.com',
                'username' => 'shamsur.rahman',
                'phone' => '01589012345',
                'photo' => null,
                'address' => 'Gazipur, Bangladesh',
                'email_verified_at' => '2025-08-15 13:10:00',
                'password' => Hash::make('111'),
                'credit' => 1800.00,
                'profession' => 'UI/UX Researcher',
                'facebook' => 'https://facebook.com/shamsur.rahman',
                'twitter' => 'https://twitter.com/shamsur.rahman',
                'google' => 'https://google.com/shamsur.rahman',
                'role' => 'user',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 13:10:00',
                'updated_at' => '2025-08-15 13:10:00',
            ],
            [
                'name' => 'Muktar Ali',
                'email' => 'muktar.ali@example.com',
                'username' => 'muktar.ali',
                'phone' => '01689012345',
                'photo' => null,
                'address' => 'Narayanganj, Bangladesh',
                'email_verified_at' => '2025-08-15 13:15:00',
                'password' => Hash::make('111'),
                'credit' => 500.00,
                'profession' => 'Data Engineer',
                'facebook' => 'https://facebook.com/muktar.ali',
                'twitter' => 'https://twitter.com/muktar.ali',
                'google' => 'https://google.com/muktar.ali',
                'role' => 'agent',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 13:15:00',
                'updated_at' => '2025-08-15 13:15:00',
            ],
            [
                'name' => 'Nayeem Islam',
                'email' => 'nayeem.islam@example.com',
                'username' => 'nayeem.islam',
                'phone' => '01790123456',
                'photo' => null,
                'address' => 'Bogra, Bangladesh',
                'email_verified_at' => '2025-08-15 13:20:00',
                'password' => Hash::make('111'),
                'credit' => 2500.00,
                'profession' => 'Machine Learning',
                'facebook' => 'https://facebook.com/nayeem.islam',
                'twitter' => 'https://twitter.com/nayeem.islam',
                'google' => 'https://google.com/nayeem.islam',
                'role' => 'user',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 13:20:00',
                'updated_at' => '2025-08-15 13:20:00',
            ],
            [
                'name' => 'Elias Sunny',
                'email' => 'elias.sunny@example.com',
                'username' => 'elias.sunny',
                'phone' => '01890123456',
                'photo' => null,
                'address' => 'Jessore, Bangladesh',
                'email_verified_at' => '2025-08-15 13:25:00',
                'password' => Hash::make('111'),
                'credit' => 4000.00,
                'profession' => 'Cloud Architect',
                'facebook' => 'https://facebook.com/elias.sunny',
                'twitter' => 'https://twitter.com/elias.sunny',
                'google' => 'https://google.com/elias.sunny',
                'role' => 'admin',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 13:25:00',
                'updated_at' => '2025-08-15 13:25:00',
            ],
            [
                'name' => 'Ziaur Rahman',
                'email' => 'ziaur.rahman@example.com',
                'username' => 'ziaur.rahman',
                'phone' => '01990123456',
                'photo' => null,
                'address' => 'Pabna, Bangladesh',
                'email_verified_at' => '2025-08-15 13:30:00',
                'password' => Hash::make('111'),
                'credit' => 1000.00,
                'profession' => 'Frontend Developer',
                'facebook' => 'https://facebook.com/ziaur.rahman',
                'twitter' => 'https://twitter.com/ziaur.rahman',
                'google' => 'https://google.com/ziaur.rahman',
                'role' => 'user',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 13:30:00',
                'updated_at' => '2025-08-15 13:30:00',
            ],
            [
                'name' => 'Meherab Hossain',
                'email' => 'meherab.hossain@example.com',
                'username' => 'meherab.hossain',
                'phone' => '01590123456',
                'photo' => null,
                'address' => 'Tangail, Bangladesh',
                'email_verified_at' => '2025-08-15 13:35:00',
                'password' => Hash::make('111'),
                'credit' => 3500.00,
                'profession' => 'Backend Developer',
                'facebook' => 'https://facebook.com/meherab.hossain',
                'twitter' => 'https://twitter.com/meherab.hossain',
                'google' => 'https://google.com/meherab.hossain',
                'role' => 'agent',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 13:35:00',
                'updated_at' => '2025-08-15 13:35:00',
            ],
            [
                'name' => 'Shahriar Nafees',
                'email' => 'shahriar.nafees@example.com',
                'username' => 'shahriar.nafees',
                'phone' => '01690123456',
                'photo' => null,
                'address' => 'Brahmanbaria, Bangladesh',
                'email_verified_at' => '2025-08-15 13:40:00',
                'password' => Hash::make('111'),
                'credit' => 800.00,
                'profession' => 'Mobile App Developer',
                'facebook' => 'https://facebook.com/shahriar.nafees',
                'twitter' => 'https://twitter.com/shahriar.nafees',
                'google' => 'https://google.com/shahriar.nafees',
                'role' => 'user',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 13:40:00',
                'updated_at' => '2025-08-15 13:40:00',
            ],
            [
                'name' => 'Naeem Islam',
                'email' => 'naeem.islam@example.com',
                'username' => 'naeem.islam',
                'phone' => '01791234567',
                'photo' => null,
                'address' => 'Comilla, Bangladesh',
                'email_verified_at' => '2025-08-15 13:45:00',
                'password' => Hash::make('111'),
                'credit' => 1200.00,
                'profession' => 'UI/UX Designer',
                'facebook' => 'https://facebook.com/naeem.islam',
                'twitter' => 'https://twitter.com/naeem.islam',
                'google' => 'https://google.com/naeem.islam',
                'role' => 'agent',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 13:45:00',
                'updated_at' => '2025-08-15 13:45:00',
            ],
            [
                'name' => 'Shakib Khan',
                'email' => 'shakib.khan@example.com',
                'username' => 'shakib.khan',
                'phone' => '01891234567',
                'photo' => null,
                'address' => 'Dhaka, Bangladesh',
                'email_verified_at' => '2025-08-15 13:50:00',
                'password' => Hash::make('111'),
                'credit' => 5000.00,
                'profession' => 'Data Scientist',
                'facebook' => 'https://facebook.com/shakib.khan',
                'twitter' => 'https://twitter.com/shakib.khan',
                'google' => 'https://google.com/shakib.khan',
                'role' => 'admin',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 13:50:00',
                'updated_at' => '2025-08-15 13:50:00',
            ],
            [
                'name' => 'Apu Biswas',
                'email' => 'apu.biswas@example.com',
                'username' => 'apu.biswas',
                'phone' => '01991234567',
                'photo' => null,
                'address' => 'Chittagong, Bangladesh',
                'email_verified_at' => '2025-08-15 13:55:00',
                'password' => Hash::make('111'),
                'credit' => 2000.00,
                'profession' => 'Project Manager',
                'facebook' => 'https://facebook.com/apu.biswas',
                'twitter' => 'https://twitter.com/apu.biswas',
                'google' => 'https://google.com/apu.biswas',
                'role' => 'user',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 13:55:00',
                'updated_at' => '2025-08-15 13:55:00',
            ],
            [
                'name' => 'Pori Moni',
                'email' => 'pori.moni@example.com',
                'username' => 'pori.moni',
                'phone' => '01591234567',
                'photo' => null,
                'address' => 'Rajshahi, Bangladesh',
                'email_verified_at' => '2025-08-15 14:00:00',
                'password' => Hash::make('111'),
                'credit' => 1500.00,
                'profession' => 'Software Engineer',
                'facebook' => 'https://facebook.com/pori.moni',
                'twitter' => 'https://twitter.com/pori.moni',
                'google' => 'https://google.com/pori.moni',
                'role' => 'agent',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 14:00:00',
                'updated_at' => '2025-08-15 14:00:00',
            ],
            [
                'name' => 'Jaya Ahsan',
                'email' => 'jaya.ahsan@example.com',
                'username' => 'jaya.ahsan',
                'phone' => '01691234567',
                'photo' => null,
                'address' => 'Khulna, Bangladesh',
                'email_verified_at' => '2025-08-15 14:05:00',
                'password' => Hash::make('111'),
                'credit' => 300.00,
                'profession' => 'Web Developer',
                'facebook' => 'https://facebook.com/jaya.ahsan',
                'twitter' => 'https://twitter.com/jaya.ahsan',
                'google' => 'https://google.com/jaya.ahsan',
                'role' => 'user',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 14:05:00',
                'updated_at' => '2025-08-15 14:05:00',
            ],
            [
                'name' => 'Nusrat Faria',
                'email' => 'nusrat.faria@example.com',
                'username' => 'nusrat.faria',
                'phone' => '01792345678',
                'photo' => null,
                'address' => 'Sylhet, Bangladesh',
                'email_verified_at' => '2025-08-15 14:10:00',
                'password' => Hash::make('111'),
                'credit' => 1000.00,
                'profession' => 'UI/UX Designer',
                'facebook' => 'https://facebook.com/nusrat.faria',
                'twitter' => 'https://twitter.com/nusrat.faria',
                'google' => 'https://google.com/nusrat.faria',
                'role' => 'agent',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 14:10:00',
                'updated_at' => '2025-08-15 14:10:00',
            ],
            [
                'name' => 'Mahiya Mahi',
                'email' => 'mahiya.mahi@example.com',
                'username' => 'mahiya.mahi',
                'phone' => '01892345678',
                'photo' => null,
                'address' => 'Barisal, Bangladesh',
                'email_verified_at' => '2025-08-15 14:15:00',
                'password' => Hash::make('111'),
                'credit' => 2500.00,
                'profession' => 'Graphic Designer',
                'facebook' => 'https://facebook.com/mahiya.mahi',
                'twitter' => 'https://twitter.com/mahiya.mahi',
                'google' => 'https://google.com/mahiya.mahi',
                'role' => 'user',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 14:15:00',
                'updated_at' => '2025-08-15 14:15:00',
            ],
            [
                'name' => 'Bidya Sinha Mim',
                'email' => 'bidya.sinha.mim@example.com',
                'username' => 'bidya.sinha.mim',
                'phone' => '01992345678',
                'photo' => null,
                'address' => 'Rangpur, Bangladesh',
                'email_verified_at' => '2025-08-15 14:20:00',
                'password' => Hash::make('111'),
                'credit' => 500.00,
                'profession' => 'Network Engineer',
                'facebook' => 'https://facebook.com/bidya.sinha.mim',
                'twitter' => 'https://twitter.com/bidya.sinha.mim',
                'google' => 'https://google.com/bidya.sinha.mim',
                'role' => 'agent',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 14:20:00',
                'updated_at' => '2025-08-15 14:20:00',
            ],
            [
                'name' => 'Shabnam Bubly',
                'email' => 'shabnam.bubly@example.com',
                'username' => 'shabnam.bubly',
                'phone' => '01592345678',
                'photo' => null,
                'address' => 'Mymensingh, Bangladesh',
                'email_verified_at' => '2025-08-15 14:25:00',
                'password' => Hash::make('111'),
                'credit' => 4000.00,
                'profession' => 'DevOps Engineer',
                'facebook' => 'https://facebook.com/shabnam.bubly',
                'twitter' => 'https://twitter.com/shabnam.bubly',
                'google' => 'https://google.com/shabnam.bubly',
                'role' => 'user',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 14:25:00',
                'updated_at' => '2025-08-15 14:25:00',
            ],
            [
                'name' => 'Bubly Aktar',
                'email' => 'bubly.aktar@example.com',
                'username' => 'bubly.aktar',
                'phone' => '01692345678',
                'photo' => null,
                'address' => 'Gazipur, Bangladesh',
                'email_verified_at' => '2025-08-15 14:30:00',
                'password' => Hash::make('111'),
                'credit' => 1800.00,
                'profession' => 'Data Scientist',
                'facebook' => 'https://facebook.com/bubly.aktar',
                'twitter' => 'https://twitter.com/bubly.aktar',
                'google' => 'https://google.com/bubly.aktar',
                'role' => 'admin',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 14:30:00',
                'updated_at' => '2025-08-15 14:30:00',
            ],
            [
                'name' => 'Srabanti Chatterjee',
                'email' => 'srabanti.chatterjee@example.com',
                'username' => 'srabanti.chatterjee',
                'phone' => '01793456789',
                'photo' => null,
                'address' => 'Narayanganj, Bangladesh',
                'email_verified_at' => '2025-08-15 14:35:00',
                'password' => Hash::make('111'),
                'credit' => 600.00,
                'profession' => 'Content Writer',
                'facebook' => 'https://facebook.com/srabanti.chatterjee',
                'twitter' => 'https://twitter.com/srabanti.chatterjee',
                'google' => 'https://google.com/srabanti.chatterjee',
                'role' => 'user',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 14:35:00',
                'updated_at' => '2025-08-15 14:35:00',
            ],
            [
                'name' => 'Koel Mallick',
                'email' => 'koel.mallick@example.com',
                'username' => 'koel.mallick',
                'phone' => '01893456789',
                'photo' => null,
                'address' => 'Cox\'s Bazar, Bangladesh',
                'email_verified_at' => '2025-08-15 14:40:00',
                'password' => Hash::make('111'),
                'credit' => 750.00,
                'profession' => 'Cyber Security Analyst',
                'facebook' => 'https://facebook.com/koel.mallick',
                'twitter' => 'https://twitter.com/koel.mallick',
                'google' => 'https://google.com/koel.mallick',
                'role' => 'agent',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 14:40:00',
                'updated_at' => '2025-08-15 14:40:00',
            ],
            [
                'name' => 'Subhasree Ganguly',
                'email' => 'subhasree.ganguly@example.com',
                'username' => 'subhasree.ganguly',
                'phone' => '01993456789',
                'photo' => null,
                'address' => 'Dinajpur, Bangladesh',
                'email_verified_at' => '2025-08-15 14:45:00',
                'password' => Hash::make('111'),
                'credit' => 2000.00,
                'profession' => 'Machine Learning Engineer',
                'facebook' => 'https://facebook.com/subhasree.ganguly',
                'twitter' => 'https://twitter.com/subhasree.ganguly',
                'google' => 'https://google.com/subhasree.ganguly',
                'role' => 'user',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 14:45:00',
                'updated_at' => '2025-08-15 14:45:00',
            ],
            [
                'name' => 'Puja Cherry',
                'email' => 'puja.cherry@example.com',
                'username' => 'puja.cherry',
                'phone' => '01593456789',
                'photo' => null,
                'address' => 'Bogra, Bangladesh',
                'email_verified_at' => '2025-08-15 14:50:00',
                'password' => Hash::make('111'),
                'credit' => 950.50,
                'profession' => 'Mobile App Developer',
                'facebook' => 'https://facebook.com/puja.cherry',
                'twitter' => 'https://twitter.com/puja.cherry',
                'google' => 'https://google.com/puja.cherry',
                'role' => 'agent',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 14:50:00',
                'updated_at' => '2025-08-15 14:50:00',
            ],
            [
                'name' => 'Achol Akhy',
                'email' => 'achol.akhy@example.com',
                'username' => 'achol.akhy',
                'phone' => '01693456789',
                'photo' => null,
                'address' => 'Jessore, Bangladesh',
                'email_verified_at' => '2025-08-15 14:55:00',
                'password' => Hash::make('111'),
                'credit' => 5000.00,
                'profession' => 'Data Engineer',
                'facebook' => 'https://facebook.com/achol.akhy',
                'twitter' => 'https://twitter.com/achol.akhy',
                'google' => 'https://google.com/achol.akhy',
                'role' => 'admin',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 14:55:00',
                'updated_at' => '2025-08-15 14:55:00',
            ],
            [
                'name' => 'Nipun Akter',
                'email' => 'nipun.akter@example.com',
                'username' => 'nipun.akter',
                'phone' => '01794567890',
                'photo' => null,
                'address' => 'Pabna, Bangladesh',
                'email_verified_at' => '2025-08-15 15:00:00',
                'password' => Hash::make('111'),
                'credit' => 300.00,
                'profession' => 'System Administrator',
                'facebook' => 'https://facebook.com/nipun.akter',
                'twitter' => 'https://twitter.com/nipun.akter',
                'google' => 'https://google.com/nipun.akter',
                'role' => 'user',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 15:00:00',
                'updated_at' => '2025-08-15 15:00:00',
            ],
            [
                'name' => 'Eamin Haque Bobby',
                'email' => 'eamin.haque@example.com',
                'username' => 'eamin.haque',
                'phone' => '01894567890',
                'photo' => null,
                'address' => 'Tangail, Bangladesh',
                'email_verified_at' => '2025-08-15 15:05:00',
                'password' => Hash::make('111'),
                'credit' => 2500.00,
                'profession' => 'Marketing Manager',
                'facebook' => 'https://facebook.com/eamin.haque',
                'twitter' => 'https://twitter.com/eamin.haque',
                'google' => 'https://google.com/eamin.haque',
                'role' => 'agent',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 15:05:00',
                'updated_at' => '2025-08-15 15:05:00',
            ],
            [
                'name' => 'Shihab Shahriar',
                'email' => 'shihab.shahriar@example.com',
                'username' => 'shihab.shahriar',
                'phone' => '01994567890',
                'photo' => null,
                'address' => 'Brahmanbaria, Bangladesh',
                'email_verified_at' => '2025-08-15 15:10:00',
                'password' => Hash::make('111'),
                'credit' => 800.00,
                'profession' => 'Cloud Engineer',
                'facebook' => 'https://facebook.com/shihab.shahriar',
                'twitter' => 'https://twitter.com/shihab.shahriar',
                'google' => 'https://google.com/shihab.shahriar',
                'role' => 'user',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 15:10:00',
                'updated_at' => '2025-08-15 15:10:00',
            ],
            [
                'name' => 'Faria Shahrin',
                'email' => 'faria.shahrin@example.com',
                'username' => 'faria.shahrin',
                'phone' => '01594567890',
                'photo' => null,
                'address' => 'Comilla, Bangladesh',
                'email_verified_at' => '2025-08-15 15:15:00',
                'password' => Hash::make('111'),
                'credit' => 3500.50,
                'profession' => 'UX Researcher',
                'facebook' => 'https://facebook.com/faria.shahrin',
                'twitter' => 'https://twitter.com/faria.shahrin',
                'google' => 'https://google.com/faria.shahrin',
                'role' => 'agent',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 15:15:00',
                'updated_at' => '2025-08-15 15:15:00',
            ],
            [
                'name' => 'Sadia Islam Mou',
                'email' => 'sadia.islam@example.com',
                'username' => 'sadia.islam',
                'phone' => '01695678901',
                'photo' => null,
                'address' => 'Dhaka, Bangladesh',
                'email_verified_at' => '2025-08-15 15:20:00',
                'password' => Hash::make('111'),
                'credit' => 500.00,
                'profession' => 'Digital Marketer',
                'facebook' => 'https://facebook.com/sadia.islam',
                'twitter' => 'https://twitter.com/sadia.islam',
                'google' => 'https://google.com/sadia.islam',
                'role' => 'user',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 15:20:00',
                'updated_at' => '2025-08-15 15:20:00',
            ],
            [
                'name' => 'Nawshin Nahar',
                'email' => 'nawshin.nahar@example.com',
                'username' => 'nawshin.nahar',
                'phone' => '01795678901',
                'photo' => null,
                'address' => 'Chittagong, Bangladesh',
                'email_verified_at' => '2025-08-15 15:25:00',
                'password' => Hash::make('111'),
                'credit' => 1500.00,
                'profession' => 'SEO Specialist',
                'facebook' => 'https://facebook.com/nawshin.nahar',
                'twitter' => 'https://twitter.com/nawshin.nahar',
                'google' => 'https://google.com/nawshin.nahar',
                'role' => 'agent',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 15:25:00',
                'updated_at' => '2025-08-15 15:25:00',
            ],
            [
                'name' => 'Ayesha Akter',
                'email' => 'ayesha.akter@example.com',
                'username' => 'ayesha.akter',
                'phone' => '01895678901',
                'photo' => null,
                'address' => 'Rajshahi, Bangladesh',
                'email_verified_at' => '2025-08-15 15:30:00',
                'password' => Hash::make('111'),
                'credit' => 2500.50,
                'profession' => 'Full-Stack Developer',
                'facebook' => 'https://facebook.com/ayesha.akter',
                'twitter' => 'https://twitter.com/ayesha.akter',
                'google' => 'https://google.com/ayesha.akter',
                'role' => 'user',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 15:30:00',
                'updated_at' => '2025-08-15 15:30:00',
            ],
            [
                'name' => 'Sumaiya Khan',
                'email' => 'sumaiya.khan@example.com',
                'username' => 'sumaiya.khan',
                'phone' => '01995678901',
                'photo' => null,
                'address' => 'Khulna, Bangladesh',
                'email_verified_at' => '2025-08-15 15:35:00',
                'password' => Hash::make('111'),
                'credit' => 1800.00,
                'profession' => 'Backend Developer',
                'facebook' => 'https://facebook.com/sumaiya.khan',
                'twitter' => 'https://twitter.com/sumaiya.khan',
                'google' => 'https://google.com/sumaiya.khan',
                'role' => 'admin',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 15:35:00',
                'updated_at' => '2025-08-15 15:35:00',
            ],
            [
                'name' => 'Nadia Afroz',
                'email' => 'nadia.afroz@example.com',
                'username' => 'nadia.afroz',
                'phone' => '01596789012',
                'photo' => null,
                'address' => 'Sylhet, Bangladesh',
                'email_verified_at' => '2025-08-15 15:40:00',
                'password' => Hash::make('111'),
                'credit' => 5000.50,
                'profession' => 'Frontend Developer',
                'facebook' => 'https://facebook.com/nadia.afroz',
                'twitter' => 'https://twitter.com/nadia.afroz',
                'google' => 'https://google.com/nadia.afroz',
                'role' => 'user',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 15:40:00',
                'updated_at' => '2025-08-15 15:40:00',
            ],
            [
                'name' => 'Sadman Faiyaz',
                'email' => 'sadman.faiyaz@example.com',
                'username' => 'sadman.faiyaz',
                'phone' => '01696789012',
                'photo' => null,
                'address' => 'Barisal, Bangladesh',
                'email_verified_at' => '2025-08-15 15:45:00',
                'password' => Hash::make('111'),
                'credit' => 900.00,
                'profession' => 'Game Developer',
                'facebook' => 'https://facebook.com/sadman.faiyaz',
                'twitter' => 'https://twitter.com/sadman.faiyaz',
                'google' => 'https://google.com/sadman.faiyaz',
                'role' => 'agent',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 15:45:00',
                'updated_at' => '2025-08-15 15:45:00',
            ],
            [
                'name' => 'Fardin Faisal',
                'email' => 'fardin.faisal@example.com',
                'username' => 'fardin.faisal',
                'phone' => '01796789012',
                'photo' => null,
                'address' => 'Rangpur, Bangladesh',
                'email_verified_at' => '2025-08-15 15:50:00',
                'password' => Hash::make('111'),
                'credit' => 1200.50,
                'profession' => 'Mobile QA Engineer',
                'facebook' => 'https://facebook.com/fardin.faisal',
                'twitter' => 'https://twitter.com/fardin.faisal',
                'google' => 'https://google.com/fardin.faisal',
                'role' => 'user',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 15:50:00',
                'updated_at' => '2025-08-15 15:50:00',
            ],
            [
                'name' => 'Nihad Khan',
                'email' => 'nihad.khan@example.com',
                'username' => 'nihad.khan',
                'phone' => '01897890123',
                'photo' => null,
                'address' => 'Mymensingh, Bangladesh',
                'email_verified_at' => '2025-08-15 15:55:00',
                'password' => Hash::make('111'),
                'credit' => 3000.00,
                'profession' => 'Software Tester',
                'facebook' => 'https://facebook.com/nihad.khan',
                'twitter' => 'https://twitter.com/nihad.khan',
                'google' => 'https://google.com/nihad.khan',
                'role' => 'agent',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 15:55:00',
                'updated_at' => '2025-08-15 15:55:00',
            ],
            [
                'name' => 'Shadab Karim',
                'email' => 'shadab.karim@example.com',
                'username' => 'shadab.karim',
                'phone' => '01997890123',
                'photo' => null,
                'address' => 'Gazipur, Bangladesh',
                'email_verified_at' => '2025-08-15 16:00:00',
                'password' => Hash::make('111'),
                'credit' => 1000.00,
                'profession' => 'UI Designer',
                'facebook' => 'https://facebook.com/shadab.karim',
                'twitter' => 'https://twitter.com/shadab.karim',
                'google' => 'https://google.com/shadab.karim',
                'role' => 'user',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 16:00:00',
                'updated_at' => '2025-08-15 16:00:00',
            ],
            [
                'name' => 'Asif Iqbal',
                'email' => 'asif.iqbal@example.com',
                'username' => 'asif.iqbal',
                'phone' => '01597890123',
                'photo' => null,
                'address' => 'Narayanganj, Bangladesh',
                'email_verified_at' => '2025-08-15 16:05:00',
                'password' => Hash::make('111'),
                'credit' => 400.00,
                'profession' => 'IT Support Specialist',
                'facebook' => 'https://facebook.com/asif.iqbal',
                'twitter' => 'https://twitter.com/asif.iqbal',
                'google' => 'https://google.com/asif.iqbal',
                'role' => 'agent',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 16:05:00',
                'updated_at' => '2025-08-15 16:05:00',
            ],
            [
                'name' => 'Tamanna Binte',
                'email' => 'tamanna.binte@example.com',
                'username' => 'tamanna.binte',
                'phone' => '01698901234',
                'photo' => null,
                'address' => 'Cox\'s Bazar, Bangladesh',
                'email_verified_at' => '2025-08-15 16:10:00',
                'password' => Hash::make('111'),
                'credit' => 2000.00,
                'profession' => 'Frontend Engineer',
                'facebook' => 'https://facebook.com/tamanna.binte',
                'twitter' => 'https://twitter.com/tamanna.binte',
                'google' => 'https://google.com/tamanna.binte',
                'role' => 'user',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 16:10:00',
                'updated_at' => '2025-08-15 16:10:00',
            ],
            [
                'name' => 'Rakib Khan',
                'email' => 'rakib.khan@example.com',
                'username' => 'rakib.khan',
                'phone' => '01798901234',
                'photo' => null,
                'address' => 'Dinajpur, Bangladesh',
                'email_verified_at' => '2025-08-15 16:15:00',
                'password' => Hash::make('111'),
                'credit' => 6000.00,
                'profession' => 'Software Architect',
                'facebook' => 'https://facebook.com/rakib.khan',
                'twitter' => 'https://twitter.com/rakib.khan',
                'google' => 'https://google.com/rakib.khan',
                'role' => 'admin',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 16:15:00',
                'updated_at' => '2025-08-15 16:15:00',
            ],
            [
                'name' => 'Hasan Mahmud',
                'email' => 'hasan.mahmud@example.com',
                'username' => 'hasan.mahmud',
                'phone' => '01898901234',
                'photo' => null,
                'address' => 'Khulna, Bangladesh',
                'email_verified_at' => '2025-08-15 16:20:00',
                'password' => Hash::make('111'),
                'credit' => 1500.00,
                'profession' => 'IT Consultant',
                'facebook' => 'https://facebook.com/hasan.mahmud',
                'twitter' => 'https://twitter.com/hasan.mahmud',
                'google' => 'https://google.com/hasan.mahmud',
                'role' => 'user',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 16:20:00',
                'updated_at' => '2025-08-15 16:20:00',
            ],
            [
                'name' => 'Nishat Sultana',
                'email' => 'nishat.sultana@example.com',
                'username' => 'nishat.sultana',
                'phone' => '01998901234',
                'photo' => null,
                'address' => 'Dhaka, Bangladesh',
                'email_verified_at' => '2025-08-15 16:25:00',
                'password' => Hash::make('111'),
                'credit' => 2500.00,
                'profession' => 'Business Analyst',
                'facebook' => 'https://facebook.com/nishat.sultana',
                'twitter' => 'https://twitter.com/nishat.sultana',
                'google' => 'https://google.com/nishat.sultana',
                'role' => 'agent',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 16:25:00',
                'updated_at' => '2025-08-15 16:25:00',
            ],
            [
                'name' => 'Afrin Sultana',
                'email' => 'afrin.sultana@example.com',
                'username' => 'afrin.sultana',
                'phone' => '01599012345',
                'photo' => null,
                'address' => 'Rangpur, Bangladesh',
                'email_verified_at' => '2025-08-15 16:30:00',
                'password' => Hash::make('111'),
                'credit' => 800.00,
                'profession' => 'Database Developer',
                'facebook' => 'https://facebook.com/afrin.sultana',
                'twitter' => 'https://twitter.com/afrin.sultana',
                'google' => 'https://google.com/afrin.sultana',
                'role' => 'user',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 16:30:00',
                'updated_at' => '2025-08-15 16:30:00',
            ],
            [
                'name' => 'Ibrahim Khalil',
                'email' => 'ibrahim.khalil@example.com',
                'username' => 'ibrahim.khalil',
                'phone' => '01699012345',
                'photo' => null,
                'address' => 'Chittagong, Bangladesh',
                'email_verified_at' => '2025-08-15 16:35:00',
                'password' => Hash::make('111'),
                'credit' => 3500.00,
                'profession' => 'System Analyst',
                'facebook' => 'https://facebook.com/ibrahim.khalil',
                'twitter' => 'https://twitter.com/ibrahim.khalil',
                'google' => 'https://google.com/ibrahim.khalil',
                'role' => 'admin',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 16:35:00',
                'updated_at' => '2025-08-15 16:35:00',
            ],
            [
                'name' => 'Sagor Ahmed',
                'email' => 'sagor.ahmed@example.com',
                'username' => 'sagor.ahmed',
                'phone' => '01799012345',
                'photo' => null,
                'address' => 'Rajshahi, Bangladesh',
                'email_verified_at' => '2025-08-15 16:40:00',
                'password' => Hash::make('111'),
                'credit' => 1200.00,
                'profession' => 'Mobile Engineer',
                'facebook' => 'https://facebook.com/sagor.ahmed',
                'twitter' => 'https://twitter.com/sagor.ahmed',
                'google' => 'https://google.com/sagor.ahmed',
                'role' => 'user',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 16:40:00',
                'updated_at' => '2025-08-15 16:40:00',
            ],
            [
                'name' => 'Farjana Akter',
                'email' => 'farjana.akter@example.com',
                'username' => 'farjana.akter',
                'phone' => '01899012345',
                'photo' => null,
                'address' => 'Sylhet, Bangladesh',
                'email_verified_at' => '2025-08-15 16:45:00',
                'password' => Hash::make('111'),
                'credit' => 950.25,
                'profession' => 'Frontend Architect',
                'facebook' => 'https://facebook.com/farjana.akter',
                'twitter' => 'https://twitter.com/farjana.akter',
                'google' => 'https://google.com/farjana.akter',
                'role' => 'agent',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 16:45:00',
                'updated_at' => '2025-08-15 16:45:00',
            ],
            [
                'name' => 'Shahadat Hossain',
                'email' => 'shahadat.hossain@example.com',
                'username' => 'shahadat.hossain',
                'phone' => '01900123456',
                'photo' => null,
                'address' => 'Barisal, Bangladesh',
                'email_verified_at' => '2025-08-15 16:50:00',
                'password' => Hash::make('111'),
                'credit' => 2000.00,
                'profession' => 'Product Manager',
                'facebook' => 'https://facebook.com/shahadat.hossain',
                'twitter' => 'https://twitter.com/shahadat.hossain',
                'google' => 'https://google.com/shahadat.hossain',
                'role' => 'user',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 16:50:00',
                'updated_at' => '2025-08-15 16:50:00',
            ],
            [
                'name' => 'Ruhul Amin',
                'email' => 'ruhul.amin@example.com',
                'username' => 'ruhul.amin',
                'phone' => '01500123456',
                'photo' => null,
                'address' => 'Mymensingh, Bangladesh',
                'email_verified_at' => '2025-08-15 16:55:00',
                'password' => Hash::make('111'),
                'credit' => 3000.00,
                'profession' => 'Project Coordinator',
                'facebook' => 'https://facebook.com/ruhul.amin',
                'twitter' => 'https://twitter.com/ruhul.amin',
                'google' => 'https://google.com/ruhul.amin',
                'role' => 'agent',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 16:55:00',
                'updated_at' => '2025-08-15 16:55:00',
            ],
            [
                'name' => 'Sumon Patwary',
                'email' => 'sumon.patwary@example.com',
                'username' => 'sumon.patwary',
                'phone' => '01600123456',
                'photo' => null,
                'address' => 'Gazipur, Bangladesh',
                'email_verified_at' => '2025-08-15 17:00:00',
                'password' => Hash::make('111'),
                'credit' => 1800.00,
                'profession' => 'UI/UX Researcher',
                'facebook' => 'https://facebook.com/sumon.patwary',
                'twitter' => 'https://twitter.com/sumon.patwary',
                'google' => 'https://google.com/sumon.patwary',
                'role' => 'user',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 17:00:00',
                'updated_at' => '2025-08-15 17:00:00',
            ],
            [
                'name' => 'Mithun Chakra',
                'email' => 'mithun.chakra@example.com',
                'username' => 'mithun.chakra',
                'phone' => '01701234567',
                'photo' => null,
                'address' => 'Narayanganj, Bangladesh',
                'email_verified_at' => '2025-08-15 17:05:00',
                'password' => Hash::make('111'),
                'credit' => 500.00,
                'profession' => 'Data Engineer',
                'facebook' => 'https://facebook.com/mithun.chakra',
                'twitter' => 'https://twitter.com/mithun.chakra',
                'google' => 'https://google.com/mithun.chakra',
                'role' => 'agent',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 17:05:00',
                'updated_at' => '2025-08-15 17:05:00',
            ],
            [
                'name' => 'Nabil Hasan',
                'email' => 'nabil.hasan@example.com',
                'username' => 'nabil.hasan',
                'phone' => '01801234567',
                'photo' => null,
                'address' => 'Cox\'s Bazar, Bangladesh',
                'email_verified_at' => '2025-08-15 17:10:00',
                'password' => Hash::make('111'),
                'credit' => 2500.00,
                'profession' => 'Machine Learning',
                'facebook' => 'https://facebook.com/nabil.hasan',
                'twitter' => 'https://twitter.com/nabil.hasan',
                'google' => 'https://google.com/nabil.hasan',
                'role' => 'user',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 17:10:00',
                'updated_at' => '2025-08-15 17:10:00',
            ],
            [
                'name' => 'Sabbir Ahmed',
                'email' => 'sabbir.ahmed@example.com',
                'username' => 'sabbir.ahmed',
                'phone' => '01901234567',
                'photo' => null,
                'address' => 'Dinajpur, Bangladesh',
                'email_verified_at' => '2025-08-15 17:15:00',
                'password' => Hash::make('111'),
                'credit' => 4000.00,
                'profession' => 'Cloud Architect',
                'facebook' => 'https://facebook.com/sabbir.ahmed',
                'twitter' => 'https://twitter.com/sabbir.ahmed',
                'google' => 'https://google.com/sabbir.ahmed',
                'role' => 'admin',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 17:15:00',
                'updated_at' => '2025-08-15 17:15:00',
            ],
            [
                'name' => 'Emon Chowdhury',
                'email' => 'emon.chowdhury@example.com',
                'username' => 'emon.chowdhury',
                'phone' => '01502345678',
                'photo' => null,
                'address' => 'Bogra, Bangladesh',
                'email_verified_at' => '2025-08-15 17:20:00',
                'password' => Hash::make('111'),
                'credit' => 1000.00,
                'profession' => 'Frontend Developer',
                'facebook' => 'https://facebook.com/emon.chowdhury',
                'twitter' => 'https://twitter.com/emon.chowdhury',
                'google' => 'https://google.com/emon.chowdhury',
                'role' => 'user',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 17:20:00',
                'updated_at' => '2025-08-15 17:20:00',
            ],
            [
                'name' => 'Jannatul Ferdous',
                'email' => 'jannatul.ferdous@example.com',
                'username' => 'jannatul.ferdous',
                'phone' => '01602345678',
                'photo' => null,
                'address' => 'Jessore, Bangladesh',
                'email_verified_at' => '2025-08-15 17:25:00',
                'password' => Hash::make('111'),
                'credit' => 3500.00,
                'profession' => 'Backend Developer',
                'facebook' => 'https://facebook.com/jannatul.ferdous',
                'twitter' => 'https://twitter.com/jannatul.ferdous',
                'google' => 'https://google.com/jannatul.ferdous',
                'role' => 'agent',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 17:25:00',
                'updated_at' => '2025-08-15 17:25:00',
            ],
            [
                'name' => 'Sanjoy Dutta',
                'email' => 'sanjoy.dutta@example.com',
                'username' => 'sanjoy.dutta',
                'phone' => '01702345678',
                'photo' => null,
                'address' => 'Pabna, Bangladesh',
                'email_verified_at' => '2025-08-15 17:30:00',
                'password' => Hash::make('111'),
                'credit' => 800.00,
                'profession' => 'Mobile App Developer',
                'facebook' => 'https://facebook.com/sanjoy.dutta',
                'twitter' => 'https://twitter.com/sanjoy.dutta',
                'google' => 'https://google.com/sanjoy.dutta',
                'role' => 'user',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 17:30:00',
                'updated_at' => '2025-08-15 17:30:00',
            ],
            [
                'name' => 'Nawshin Rahman',
                'email' => 'nawshin.rahman@example.com',
                'username' => 'nawshin.rahman',
                'phone' => '01803456789',
                'photo' => null,
                'address' => 'Tangail, Bangladesh',
                'email_verified_at' => '2025-08-15 17:35:00',
                'password' => Hash::make('111'),
                'credit' => 1200.00,
                'profession' => 'UI/UX Designer',
                'facebook' => 'https://facebook.com/nawshin.rahman',
                'twitter' => 'https://twitter.com/nawshin.rahman',
                'google' => 'https://google.com/nawshin.rahman',
                'role' => 'agent',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 17:35:00',
                'updated_at' => '2025-08-15 17:35:00',
            ],
            [
                'name' => 'Farhana Mili',
                'email' => 'farhana.mili@example.com',
                'username' => 'farhana.mili',
                'phone' => '01903456789',
                'photo' => null,
                'address' => 'Brahmanbaria, Bangladesh',
                'email_verified_at' => '2025-08-15 17:40:00',
                'password' => Hash::make('111'),
                'credit' => 5000.00,
                'profession' => 'Data Scientist',
                'facebook' => 'https://facebook.com/farhana.mili',
                'twitter' => 'https://twitter.com/farhana.mili',
                'google' => 'https://google.com/farhana.mili',
                'role' => 'admin',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 17:40:00',
                'updated_at' => '2025-08-15 17:40:00',
            ],
            [
                'name' => 'Sabila Nur',
                'email' => 'sabila.nur@example.com',
                'username' => 'sabila.nur',
                'phone' => '01503456789',
                'photo' => null,
                'address' => 'Comilla, Bangladesh',
                'email_verified_at' => '2025-08-15 17:45:00',
                'password' => Hash::make('111'),
                'credit' => 2000.00,
                'profession' => 'Project Manager',
                'facebook' => 'https://facebook.com/sabila.nur',
                'twitter' => 'https://twitter.com/sabila.nur',
                'google' => 'https://google.com/sabila.nur',
                'role' => 'user',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 17:45:00',
                'updated_at' => '2025-08-15 17:45:00',
            ],
            [
                'name' => 'Tanjin Tisha',
                'email' => 'tanjin.tisha@example.com',
                'username' => 'tanjin.tisha',
                'phone' => '01604567890',
                'photo' => null,
                'address' => 'Dhaka, Bangladesh',
                'email_verified_at' => '2025-08-15 17:50:00',
                'password' => Hash::make('111'),
                'credit' => 1500.00,
                'profession' => 'Software Engineer',
                'facebook' => 'https://facebook.com/tanjin.tisha',
                'twitter' => 'https://twitter.com/tanjin.tisha',
                'google' => 'https://google.com/tanjin.tisha',
                'role' => 'agent',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 17:50:00',
                'updated_at' => '2025-08-15 17:50:00',
            ],
            [
                'name' => 'Safia Akter',
                'email' => 'safia.akter@example.com',
                'username' => 'safia.akter',
                'phone' => '01704567890',
                'photo' => null,
                'address' => 'Chittagong, Bangladesh',
                'email_verified_at' => '2025-08-15 17:55:00',
                'password' => Hash::make('111'),
                'credit' => 300.00,
                'profession' => 'Web Developer',
                'facebook' => 'https://facebook.com/safia.akter',
                'twitter' => 'https://twitter.com/safia.akter',
                'google' => 'https://google.com/safia.akter',
                'role' => 'user',
                'status' => 'active',
                'remember_token' => Str::random(10),
                'created_at' => '2025-08-15 17:55:00',
                'updated_at' => '2025-08-15 17:55:00',
            ],
        ];

        DB::table('users')->insert($users);
    }
}
